---
deployment:
  tasks:
    - export DEPLOYPATH=/home/skydivec/sites/portal.skydivect.com/
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R lang $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp artisan.php $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp phpunit.xml $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
